"""Run with Blender: imports the browser-exported architectural study into editable .blend."""
from pathlib import Path
import bpy
from mathutils import Vector
root=Path('/workspace/shared/shibuya-artifacts')
bpy.ops.wm.read_factory_settings(use_empty=True)
bpy.ops.import_scene.gltf(filepath=str(root/'shibuya-architectural-study.glb'))
for obj in list(bpy.data.objects):
 if obj.type=='LIGHT': bpy.data.objects.remove(obj,do_unlink=True)
world=bpy.data.worlds.new('Tokyo daylight');bpy.context.scene.world=world;world.use_nodes=True
world.node_tree.nodes['Background'].inputs[0].default_value=(0.55,0.65,0.72,1)
world.node_tree.nodes['Background'].inputs[1].default_value=.65
light=bpy.data.lights.new('Afternoon sun','SUN');light.energy=2.2;light.angle=.16
sun=bpy.data.objects.new('Afternoon sun',light);bpy.context.collection.objects.link(sun);sun.rotation_euler=(.5,-.45,-.4)
camdata=bpy.data.cameras.new('District camera');cam=bpy.data.objects.new('District camera',camdata);bpy.context.collection.objects.link(cam)
cam.location=(-390,-410,330);target=Vector((0,0,28));cam.rotation_euler=(target-cam.location).to_track_quat('-Z','Y').to_euler();camdata.type='ORTHO';camdata.ortho_scale=640;bpy.context.scene.camera=cam
scene=bpy.context.scene;scene.render.engine='CYCLES';scene.cycles.samples=24
scene.cycles.use_denoising=False  # Current Blender build has no OpenImageDenoise support.
scene.render.threads_mode='FIXED';scene.render.threads=4
scene.render.resolution_x=1600;scene.render.resolution_y=1200;scene.render.resolution_percentage=100
scene['provenance']='Original Shibuya-inspired architectural study; not surveyed/photogrammetric. Generated by scripts/export-city.py.'
scene['units']='metres; compressed gameplay scale'
bpy.ops.wm.save_as_mainfile(filepath=str(root/'shibuya-architectural-study.blend'))
meshes=[o for o in bpy.data.objects if o.type=='MESH'];assert len(meshes)>100
print('BLENDER_VALIDATED',len(meshes),'meshes;',len(bpy.data.materials),'materials;',len(bpy.data.images),'images')
