#!/usr/bin/env python3
"""Actual friendly-acquisition UI and explicit synthetic callback-failure harness."""
import json, os, re
from pathlib import Path
from playwright.sync_api import sync_playwright, expect
OUT=Path(os.getenv('MARKET_ACQUISITIONS_OUT','/workspace/shared/shibuya-artifacts/market-acquisitions')); OUT.mkdir(parents=True,exist_ok=True)
URL=os.getenv('PLAYTEST_URL','http://127.0.0.1:5173'); checks=[]; errors=[]
def ok(message): checks.append(message); print('PASS',message,flush=True)
def btn(root,name): return root.get_by_role('button',name=name,exact=True)
def read(page): return page.evaluate("async()=> (await import('/src/persistence.ts')).loadGame()")
def save(page):
 btn(page,'設定・保存').click(); d=page.get_by_role('dialog',name='設定と会社データ'); btn(d,'今すぐ保存する').click(); expect(page.get_by_role('alert')).to_contain_text('保存しました'); btn(d,'閉じる').click(); return read(page)
def overflow(page): assert page.evaluate('document.documentElement.scrollWidth<=innerWidth')
with sync_playwright() as playwright:
 browser=playwright.chromium.launch(executable_path='/usr/bin/chromium',args=['--enable-unsafe-swiftshader']); context=browser.new_context(viewport={'width':640,'height':600}); context.route('**/src/city/CityView.tsx*',lambda route:route.fulfill(status=200,content_type='application/javascript',body='export default function CityView(){return null}')); page=context.new_page(); page.set_default_timeout(60000)
 page.on('pageerror',lambda e:errors.append(str(e))); page.on('console',lambda m:errors.append(m.text) if m.type=='error' else None); page.goto(URL)
 fixture=page.evaluate('''async()=>{const e=await import('/src/sim/engine.ts'),p=await import('/src/persistence.ts'),m=await import('/src/sim/marketAcquisitions.ts');let s=e.createGame('市場買収UI検証株式会社',812);s.cash=900000000;s.reputation=100;s.listed=true;s.settings.quality='low';s=e.applyAction(s,{type:'openStore',lotId:'dogenzaka-02',style:'standard'});s=e.applyAction(s,{type:'updateStore',storeId:s.stores[0].id,changes:{manager:true,price:750,quality:85}});const target=m.getMarketAcquisitionTargets(s).filter(t=>t.market==='Growth').sort((a,b)=>a.quotePrice-b.quotePrice)[0];s=e.applyAction(s,{type:'buyStock',stockId:target.stockId,shares:10});return {state:s,target,envelope:await p.createEnvelope(s)}}''')
 path=OUT/'fixture.json';path.write_text(json.dumps(fixture['envelope'],ensure_ascii=False));page.locator('input[type=file]').set_input_files(str(path));btn(page,'株式市場').click();page.set_viewport_size({'width':1280,'height':960});btn(page,'友好的買収').click()
 expect(page.locator('.ma-card')).to_have_count(12);expect(page.locator('.market-acquisitions')).to_contain_text('100');btn(page,'次へ').click();expect(page.locator('.ma-pagination')).to_contain_text('2 / 9');btn(page,'前へ').click()
 page.get_by_label('買収候補の市場').select_option('Growth');assert 0<page.locator('.ma-card').count()<=12;page.get_by_label('買収候補の業種').select_option('通信・IT');overflow(page);page.get_by_label('買収候補の業種').select_option('all');page.get_by_label('買収候補の市場').select_option('all');page.get_by_label('買収候補の状態').select_option('affordable');expect(page.locator('.ma-card').first).to_be_visible();page.get_by_label('買収候補の状態').select_option('all')
 ok('100 acquisition candidates paginated 12/page with functioning market/sector/cash filters')
 target=fixture['target'];page.get_by_label('買収候補を検索').fill(target['name']);expect(page.locator('.ma-card')).to_have_count(1);btn(page,'調査・買収条件を見る').click();dialog=page.get_by_role('dialog');expect(dialog).to_contain_text('ゲーム専用の企業買収評価額');expect(dialog).to_contain_text('調査の完了が必要');dialog.get_by_role('button',name=re.compile('有料調査の支払を確認')).click();expect(dialog).to_contain_text('返金不可');btn(dialog,'条件に戻る').click();assert read(page)==fixture['state'];dialog.get_by_role('button',name=re.compile('有料調査の支払を確認')).click();btn(dialog,'調査費を支払う').click();expect(dialog).to_contain_text('調査結果');expect(dialog.get_by_role('group',name='買収後の運営方式')).to_be_visible()
 btn(dialog,'買収条件を閉じる').click();researched=save(page);assert researched['cash']==fixture['state']['cash']-target['researchCost'];assert len(researched['marketAcquisitions']['research'])==1 and researched['marketAcquisitions']['companies']==[]
 ok('paid research requires confirmation; cancel unchanged; fee debited once and results disclose quality/risks')
 btn(page,'調査・買収条件を見る').click();dialog=page.get_by_role('dialog');dialog.get_by_role('button',name=re.compile('グループへ統合')).click();expect(dialog.get_by_role('button',name=re.compile('グループへ統合'))).to_have_attribute('aria-pressed','true');btn(dialog,'買収と引継ぎを確認').click();expect(dialog).to_contain_text('今週の予想利益');expect(dialog).to_contain_text('保有株式の時価');page.screenshot(path=str(OUT/'integrated-confirm.png'));btn(dialog,'条件に戻る').click();dialog.get_by_role('button',name=re.compile('独立運営を維持')).click();btn(dialog,'買収と引継ぎを確認').click();expected=page.evaluate("async(s)=> (await import('/src/sim/engine.ts')).applyAction(s,{type:'acquireMarketCompany',stockId:'"+target['stockId']+"',mode:'autonomous'})",researched);btn(dialog,'友好的買収を実行する').click();expect(dialog).to_contain_text('経営の引継ぎ中');btn(dialog,'買収条件を閉じる').click();acquired=save(page);assert acquired==expected;assert not any(p['stockId']==target['stockId'] for p in acquired['positions']);assert len(acquired['marketAcquisitions']['companies'])==1
 ok('both operating modes selectable; confirm shows true forecast; acquisition equals engine result including stock credit/removal')
 btn(page,'株式投資').click();page.get_by_label('銘柄を検索').fill(target['name']);expect(page.locator('tbody tr')).to_have_count(1);expect(btn(page.locator('tbody tr'),'買う')).to_be_disabled();expect(page.locator('tbody tr')).to_contain_text('通常売買終了');page.set_viewport_size({'width':640,'height':600});page.reload();page.get_by_role('button',name=re.compile('市場買収UI検証株式会社 を続ける')).click();btn(page,'株式市場').click();btn(page,'友好的買収').click();assert read(page)==acquired;page.get_by_label('買収候補の状態').select_option('owned');expect(page.locator('.ma-card')).to_have_count(1)
 for _ in range(2):
  page.get_by_role('button',name=re.compile('週を終了する')).click();d=page.get_by_role('dialog',name=re.compile('第.*週の営業計画'));btn(d,'営業して週を進める').click();btn(page.get_by_role('dialog',name=re.compile('第.*週の経営レポート')),'街に戻る').click()
 expect(page.locator('.ma-card')).to_contain_text('稼働中');page.set_viewport_size({'width':1280,'height':960});page.screenshot(path=str(OUT/'operating-company.png'));ok('acquired stock trading disabled; saved ownership reloads; actual week advancement reaches operating status')
 page.set_viewport_size({'width':390,'height':844});overflow(page);btn(page,'調査・買収条件を見る').click();expect(page.get_by_role('dialog')).to_contain_text('選択した運営方式');overflow(page);page.screenshot(path=str(OUT/'mobile-owned.png'));btn(page.get_by_role('dialog'),'買収条件を閉じる').click();ok('390px owned-company detail and candidate list readable with no horizontal overflow')
 # Isolate callback failure behavior without mutating the actual application or simulation.
 harness=context.new_page();harness.goto(URL)
 harness.evaluate('''async(s)=>{const React=(await import('/node_modules/.vite/deps/react.js')).default;const DOM=(await import('/node_modules/.vite/deps/react-dom_client.js')).default;const Panel=(await import('/src/ui/MarketAcquisitionsPanel.tsx')).default;document.getElementById('root').style.display='none';const host=document.createElement('div');document.body.append(host);window.__marketHarness=DOM.createRoot(host);window.__marketHarness.render(React.createElement(Panel,{state:s,onAction:()=>false}));}''',fixture['state'])
 harness.get_by_label('買収候補を検索').fill(target['name']);btn(harness,'調査・買収条件を見る').click();d=harness.get_by_role('dialog');d.get_by_role('button',name=re.compile('有料調査の支払を確認')).click();btn(d,'調査費を支払う').click();expect(d).to_contain_text('操作を完了できませんでした');expect(btn(d,'調査費を支払う')).to_be_enabled();btn(d,'買収条件を閉じる').click();harness.evaluate("async(s)=>{const React=(await import('/node_modules/.vite/deps/react.js')).default;const Panel=(await import('/src/ui/MarketAcquisitionsPanel.tsx')).default;window.__marketHarness.render(React.createElement(Panel,{state:s,onAction:()=>false}));}",researched);btn(harness,'調査・買収条件を見る').click();d=harness.get_by_role('dialog');btn(d,'買収と引継ぎを確認').click();btn(d,'友好的買収を実行する').click();expect(d).to_contain_text('操作を完了できませんでした');expect(btn(d,'友好的買収を実行する')).to_be_enabled();harness.close();ok('false action callback preserves both paid-research and acquisition confirmations with error and retry')
 assert not errors,errors;ok('no browser errors in actual application flow');browser.close();(OUT/'results.json').write_text(json.dumps({'passed':checks,'errors':errors,'fixtureNotice':'Funded synthetic UI fixture; CityView stubbed to isolate DOM behavior. Not 3D or campaign duration evidence.'},ensure_ascii=False,indent=2))
