import { useEffect, useRef, useState } from 'react';
import type { ReactNode } from 'react';
import { ArrowDownLeft, ArrowUpRight, Building2, ChevronRight, Coffee, Landmark, Layers, MapPin, Pause, Palette, Flag, Settings, TrendingUp, X } from 'lucide-react';
import CityView from './city/CityView';
import { createGame, applyAction, previewWeek, advanceWeek, getSummary, operatingConditions, getStoreOperatingInsight } from './sim/engine';
import { LOTS, ACQUISITION_TARGETS } from './data/district';
import MarketPanel from './ui/MarketPanel';
import DealsPanel from './ui/DealsPanel';
import DesignPanel, { type DesignChoice } from './ui/DesignPanel';
import DevelopmentPanel from './ui/DevelopmentPanel';
import ProgressionPanel from './ui/ProgressionPanel';
import StoreOpeningPanel from './ui/StoreOpeningPanel';
import OpeningResults from './ui/OpeningResults';
import { StoreOperatingInsightPanel } from './ui/StoreOperatingInsightPanel';
import CapitalPlanningPanel, { type CapitalPlanningDraft } from './ui/CapitalPlanningPanel';
import RailProjectsPanel from './ui/RailProjectsPanel';
import GrowthMilestonePanel from './ui/GrowthMilestonePanel';
import { getInvestmentMemo, type InvestmentIntent, type InvestmentVisit, type InvestmentMemo } from './ui/investmentPlanning';
import { runManagedWeeks } from './sim/managedWeeks';
import { loadGame, saveGame, exportGame, importGame, listBackups, restoreBackup } from './persistence';
import type { GameState, GameAction, Store, StoreStyle, DistrictId } from './model';

type Page = 'city' | 'stores' | 'finance' | 'stocks' | 'group' | 'history' | 'deals' | 'progression' | 'development';
const money = (n: number) => '¥' + Math.round(n).toLocaleString('ja-JP');
const compact = (n: number) => Math.abs(n) >= 100000000 ? `${(n / 100000000).toFixed(2)}億円` : Math.abs(n) >= 10000 ? `${(n / 10000).toFixed(1)}万円` : money(n);
const styles: Record<StoreStyle, string> = { standard: '街角カフェ', premium: 'プレミアム', takeaway: 'テイクアウト' };
const districtNames: Record<string,string> = { center: '渋谷駅前', dogenzaka: '道玄坂', miyashita: '宮下公園', sakuragaoka: '桜丘' };
function Metric({ label, value, note, good }: { label: string; value: ReactNode; note?: string; good?: boolean }) { return <div className="metric"><span>{label}</span><strong className={good === true ? 'positive' : good === false ? 'negative' : ''}>{value}</strong>{note && <small>{note}</small>}</div>; }
function Modal({ title, children, close, wide }: { title: string; children: ReactNode; close: () => void; wide?: boolean }) { return <div className="modal-shade" onMouseDown={e => e.target === e.currentTarget && close()}><section className={'modal ' + (wide ? 'wide' : '')} role="dialog" aria-modal="true" aria-label={title}><header><div><span className="eyebrow">SHIBUYA CAPITAL</span><h2>{title}</h2></div><button className="icon-button" onClick={close} aria-label="閉じる"><X size={20}/></button></header>{children}</section></div>; }

export default function App() {
  const [state, setState] = useState<GameState | null>(null);
  const stateRef = useRef<GameState | null>(null);
  const [saved, setSaved] = useState<GameState | null>(null);
  const [ready, setReady] = useState(false);
  const [companyName, setCompanyName] = useState('渋谷珈琲株式会社');
  const [page, setPage] = useState<Page>('city');
  const [marketEntry, setMarketEntry] = useState<'investment'|'acquisitions'>('investment');
  const [selectedLotId, setSelectedLotId] = useState<string | null>(null);
  const [focusRailDistrict, setFocusRailDistrict] = useState<DistrictId | null>(null);
  const [focusStoreLotId, setFocusStoreLotId] = useState<string | null>(null);
  const [investmentPlan, setInvestmentPlan] = useState<{ visit: InvestmentVisit; memo: InvestmentMemo } | null>(null);
  const [investmentVisit, setInvestmentVisit] = useState<InvestmentVisit | null>(null);
  const investmentSequence = useRef(0);
  const [financeDraft, setFinanceDraft] = useState<CapitalPlanningDraft | undefined>();
  const [growthMilestone, setGrowthMilestone] = useState<{ before: GameState; after: GameState } | null>(null);
  const [viewMode, setViewMode] = useState<'normal'|'demand'|'ownership'>('normal');
  const [modal, setModal] = useState<'week'|'settings'|'report'|'new'|'recovery'|'design'|'batch'|null>(null);
  const [design, setDesign] = useState<DesignChoice>(() => { try { const v=localStorage.getItem('shibuya-design'); return v==='metro'||v==='night'?v:'daylight'; } catch { return 'daylight'; } });
  useEffect(() => { document.documentElement.dataset.design=design; try { localStorage.setItem('shibuya-design',design); } catch { /* The theme still works if storage is unavailable. */ } },[design]);
  const [message, setMessage] = useState('');
  const [busy, setBusy] = useState(false);
  const [runWeeks, setRunWeeks] = useState<1|4|13>(1);
  const [batchResult, setBatchResult] = useState<Awaited<ReturnType<typeof runManagedWeeks>> | null>(null);
  const [batchDone, setBatchDone] = useState(0);
  const stopRun = useRef(false);
  const [onboarding, setOnboarding] = useState(true);
  const [style, setStyle] = useState<StoreStyle>('standard');
  const [backups, setBackups] = useState<Awaited<ReturnType<typeof listBackups>>>([]);
  const fileRef = useRef<HTMLInputElement>(null);
  useEffect(() => { loadGame().then(setSaved).catch(e => setMessage(String(e))).finally(() => setReady(true)); }, []);
  useEffect(() => { stateRef.current = state; }, [state]);
  useEffect(() => {
    if (!investmentVisit) return;
    const destination = investmentVisit.intent.kind === 'store' ? 'city' : investmentVisit.intent.kind === 'rail' ? 'development' : 'stocks';
    if (page !== destination) setInvestmentVisit(null);
  }, [page, investmentVisit]);
  useEffect(() => { if (!message) return; const id = setTimeout(() => setMessage(''), 8000); return () => clearTimeout(id); }, [message]);
  useEffect(() => { if (modal === 'settings' || modal === 'recovery') listBackups().then(setBackups).catch(e => setMessage(String(e))); }, [modal]);
  const fail = (e: unknown) => setMessage(e instanceof Error ? e.message : String(e));
  const act = (action: GameAction) => { if (!state || busy) return false; try { const before = stateRef.current ?? state; const next = applyAction(before, action); stateRef.current = next; setState(next); if (action.type === 'ipo' && !before.listed && next.listed) { setModal(null); setGrowthMilestone({ before, after: next }); } if (action.type === 'closeStore') setFocusStoreLotId(null); return true; } catch(e) { fail(e); return false; } };
  const start = async () => { if (busy) return; setBusy(true); try { const next = createGame(companyName.trim() || '渋谷珈琲株式会社', crypto.getRandomValues(new Uint32Array(1))[0]); await saveGame(next); setState(next); stateRef.current = next; setSaved(next); setModal(null); setRunWeeks(1); setBatchResult(null); setPage('city'); setSelectedLotId(null); setFocusRailDistrict(null); setFocusStoreLotId(null); setInvestmentPlan(null); setInvestmentVisit(null); setGrowthMilestone(null); setFinanceDraft(undefined); setOnboarding(true); } catch(e) { fail(e); } finally { setBusy(false); } };
  const finishWeek = async () => {
    if (!state || busy) return;
    setBusy(true); setBatchDone(0); stopRun.current=false;
    try {
      if (runWeeks===1) {
        const next=advanceWeek(state); await saveGame(next); setState(next); stateRef.current=next; setSaved(next); setModal('report');
      } else {
        const result=await runManagedWeeks(state,runWeeks,{commit:saveGame,shouldCancel:()=>stopRun.current,onCommit:(next)=>{setState(next);stateRef.current=next;setSaved(next);setBatchDone(n=>n+1);}});
        setBatchResult(result); setState(result.state); stateRef.current=result.state; setSaved(result.state); setRunWeeks(1);
        if(result.reports.length) setModal('batch'); else if(result.stopReason)setMessage(result.stopReason);
      }
    } catch(e) { fail(e); } finally { setBusy(false); }
  };
  const save = async () => { if (!state || busy) return; setBusy(true); try { await saveGame(state); setSaved(state); setMessage('現在の経営状況を保存しました。'); } catch(e) { fail(e); } finally { setBusy(false); } };
  const openRealCity = async () => { if (busy) return; setBusy(true); try { if (state) { await saveGame(stateRef.current ?? state); } window.location.assign('./real-shibuya.html'); } catch(e) { fail(e); setBusy(false); } };
  const restore = async (key: string) => { if (busy) return; setBusy(true); try { const next = await restoreBackup(key); stateRef.current = next; setState(next); setSaved(next); setModal(null); setSelectedLotId(null); setFocusRailDistrict(null); setFocusStoreLotId(null); setInvestmentPlan(null); setInvestmentVisit(null); setGrowthMilestone(null); setFinanceDraft(undefined); setRunWeeks(1); setMessage('バックアップを復元しました。'); } catch(e) { fail(e); } finally { setBusy(false); } };
  const importFile = async (file: File) => { setBusy(true); try { const next = await importGame(file); await saveGame(next); stateRef.current = next; setState(next); setSaved(next); setModal(null); setSelectedLotId(null); setFocusRailDistrict(null); setFocusStoreLotId(null); setInvestmentPlan(null); setInvestmentVisit(null); setGrowthMilestone(null); setFinanceDraft(undefined); setRunWeeks(1); setMessage('会社データを読み込みました。'); } catch(e) { fail(e); } finally { setBusy(false); } };
  const fileInput = <input ref={fileRef} type="file" accept=".json,application/json" hidden onChange={e => { const file = e.target.files?.[0]; if (file) void importFile(file); e.target.value = ''; }}/ >;
  const designDialog = modal==='design' && <Modal title="デザインを選ぶ" close={()=>setModal(null)} wide><DesignPanel value={design} onChange={setDesign}/></Modal>;
  const designButton = <button className="design-trigger" onClick={()=>setModal('design')} aria-label="デザインを選ぶ"><Palette size={16}/><span>デザイン</span></button>;
  if (!state) return <main className="welcome"><div className="welcome-design">{designButton}</div>{designDialog}<div className="welcome-grid"/><div className="welcome-content"><span className="eyebrow">TOKYO BUSINESS SIMULATION</span><h1>SHIBUYA<br/><em>CAPITAL.</em></h1><p className="welcome-lead">一軒の珈琲店から、<br/>この街の未来をつくる。</p><p className="welcome-copy">渋谷で起業し、利益を次の挑戦へ。<br/>店舗、不動産、投資、そして巨大企業グループへ。</p><div className="welcome-actions">{!ready ? <p>会社データを確認中…</p> : <>{saved && <button className="primary" onClick={() => { setState(saved); stateRef.current = saved; setOnboarding(false); }}><span>{saved.companyName} を続ける<small>第{saved.week}週 · {compact(saved.cash)}</small></span><ArrowUpRight size={20}/></button>}<label>会社名<input value={companyName} maxLength={40} onChange={e => setCompanyName(e.target.value)} /></label><button className={saved ? 'secondary' : 'primary'} disabled={busy} onClick={() => saved ? setModal('new') : void start()}>新しい会社を設立 <ChevronRight size={18}/></button><button className="text-button" disabled={busy} onClick={() => fileRef.current?.click()}>保存ファイルを読み込む</button><button className="text-button" disabled={busy} onClick={() => setModal('recovery')}>保存履歴から復元</button></>}<button className="text-button" disabled={busy} onClick={()=>void openRealCity()}>実際の渋谷を3Dで見る <ArrowUpRight size={15}/></button><small>初期資金 1,200万円 · 週ごとに進行 · ログイン不要</small></div></div><div className="welcome-side"><span>35°39′N / 139°42′E</span><div className="skyline">{Array.from({length:18},(_,i)=><i key={i} style={{height: `${90+((i*79)%250)}px`, width:`${20+i%4*12}px`}}/>)}</div><div className="welcome-caption"><span>CHAPTER 01</span><h2>渋谷、その先へ。</h2><p>小さな決断が、大きな街を動かす。</p></div></div>{fileInput}{message && <div className="toast" role="alert">{message}<button onClick={() => setMessage('')} aria-label="閉じる"><X size={16}/></button></div>}{modal === 'recovery' && <Modal title="保存履歴から復元" close={() => setModal(null)}><p>週末の自動保存から、会社の経営を再開できます。</p>{!backups.length && <p className="muted">このブラウザーに保存履歴はありません。</p>}{backups.map(b=><button className="backup" key={b.key} disabled={busy} onClick={() => void restore(b.key)}><span>{b.companyName} · 第{b.week}週</span><small>{new Date(b.savedAt).toLocaleString('ja-JP')}</small></button>)}</Modal>}{modal === 'new' && <Modal title="新しい会社を設立" close={() => setModal(null)}><p>現在の保存データを新しい会社で置き換えます。必要な場合は先に現在の会社を続け、設定から保存ファイルを書き出してください。</p><button className="primary" disabled={busy} onClick={() => void start()}>設立する</button></Modal>}</main>;

  const summary = getSummary(state);
  const forecast = previewWeek(state);
  const economy = operatingConditions(state);
  const lot = LOTS.find(l => l.id === selectedLotId);
  const store = state.stores.find(s => s.lotId === selectedLotId);
  const property = state.properties.find(p => p.lotId === selectedLotId);
  const tabs: {id:Page;label:string;icon:ReactNode}[] = [{id:'city',label:'街を探索',icon:<MapPin size={18}/>},{id:'stores',label:'店舗経営',icon:<Coffee size={18}/>},{id:'finance',label:'財務・不動産',icon:<Landmark size={18}/>},{id:'stocks',label:'株式市場',icon:<TrendingUp size={18}/>},{id:'deals',label:'営業・提案',icon:<ArrowDownLeft size={18}/>},{id:'group',label:'グループ',icon:<Building2 size={18}/>},{id:'development',label:'街区開発',icon:<Building2 size={18}/>},{id:'progression',label:'成長戦略',icon:<Flag size={18}/>},{id:'history',label:'経営記録',icon:<Layers size={18}/>}];
  const selectLot = (id: string) => { setFocusRailDistrict(null); setFocusStoreLotId(null); setSelectedLotId(id); setPage('city'); };
  const viewStore = (id: string) => {
    const current = stateRef.current ?? state;
    if (!current.stores.some(candidate => candidate.lotId === id)) { setMessage('この場所の店舗は現在営業していません。'); return; }
    setModal(null); setFocusRailDistrict(null); setSelectedLotId(id); setFocusStoreLotId(id); setPage('city');
  };
  const planInvestment = (intent: InvestmentIntent) => {
    const current = stateRef.current ?? state;
    const visit = { id: `${current.id}:plan:${++investmentSequence.current}`, intent };
    const memo = getInvestmentMemo(current, visit);
    if (!memo) { setMessage('この投資の条件が変わりました。対象の状態を確認してください。'); return; }
    setInvestmentPlan({ visit, memo }); setInvestmentVisit(null); setModal(null); setPage('finance');
  };
  const returnToInvestment = () => {
    if (!investmentPlan) return;
    const intent = investmentPlan.visit.intent;
    setInvestmentVisit({ id: `${investmentPlan.visit.id}:return:${++investmentSequence.current}`, intent });
    setModal(null);
    if (intent.kind === 'store') { setStyle(intent.style); selectLot(intent.lotId); }
    else setPage(intent.kind === 'rail' ? 'development' : 'stocks');
  };
  const actionButton = (label:string, action:GameAction, className='secondary') => <button className={className} disabled={busy || state.gameOver} onClick={() => act(action)}>{label}</button>;
  const storeControls = (s:Store) => <div className="store-controls">{!state.gameOver && <StoreOperatingInsightPanel key={s.id} insight={getStoreOperatingInsight(state,s.id)} storeName={s.name}/>}<label>店舗名<input key={s.id+'name'} defaultValue={s.name} maxLength={35} onBlur={e => { if (e.target.value.trim() && e.target.value !== s.name) act({type:'updateStore',storeId:s.id,changes:{name:e.target.value.trim()}}); }}/></label><div className="field-grid"><label>販売価格（円）<input type="number" key={s.id+'price'+s.price} defaultValue={s.price} min={200} max={2500} step={50} onBlur={e => act({type:'updateStore',storeId:s.id,changes:{price:Number(e.target.value)}})}/></label><label>従業員数<input type="number" key={s.id+'staff'+s.staff} defaultValue={s.staff} min={1} max={30} onBlur={e => act({type:'updateStore',storeId:s.id,changes:{staff:Number(e.target.value)}})}/></label></div><label>内装・営業スタイル（変更80万円）<select value={s.style} onChange={e => act({type:'updateStore',storeId:s.id,changes:{style:e.target.value as StoreStyle}})}>{Object.entries(styles).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>品質 <span>{s.quality}</span><input type="range" min={20} max={100} step={5} value={s.quality} onChange={e => act({type:'updateStore',storeId:s.id,changes:{quality:Number(e.target.value)}})}/></label><label>週間広告費<input type="number" key={s.id+'marketing'+s.marketing} defaultValue={s.marketing} min={0} step={10000} onBlur={e => act({type:'updateStore',storeId:s.id,changes:{marketing:Number(e.target.value)}})}/></label><label className="toggle"><input type="checkbox" checked={s.manager} onChange={e => act({type:'updateStore',storeId:s.id,changes:{manager:e.target.checked}})}/><span>店長に運営を委任<small>店長費 週{compact(72_000*economy.wages)} · 入力した人員・広告の配分枠で運営を調整</small></span></label><div className="button-row">{s.level<5?actionButton(`設備増強 ${compact(1200000*s.level)} · Lv.${s.level}`,{type:'upgradeStore',storeId:s.id}):<span className="owned-label">設備 最大レベル</span>}<button className="danger-link" disabled={state.gameOver} onClick={() => { if (window.confirm(`${s.name} を閉店しますか？`)) act({type:'closeStore',storeId:s.id}); }}>閉店</button></div></div>;
  return <main className="game-shell">{growthMilestone && <GrowthMilestonePanel before={growthMilestone.before} after={growthMilestone.after} onClose={()=>setGrowthMilestone(null)} onNavigate={target=>{if(target==='market') setMarketEntry('acquisitions');setPage(target==='market'?'stocks':target);}}/>}{designDialog}<aside className="rail"><a className="wordmark" href="#" onClick={e => {e.preventDefault();setPage('city');}}>S<span>C</span><i/></a><nav>{tabs.map(t=><button key={t.id} className={page===t.id?'active':''} title={t.label} onClick={()=>{if(t.id==='stocks') setMarketEntry('investment');setPage(t.id);}}>{t.icon}<span>{t.label}</span></button>)}</nav><button className="rail-settings" aria-label="設定・保存" onClick={()=>setModal('settings')}><Settings size={20}/><span>設定・保存</span></button></aside><div className="workspace"><header className="topbar"><div className="company"><span className="eyebrow">SHIBUYA CAPITAL</span><h1>{state.companyName}{state.listed && <b>上場</b>}</h1></div><div className="top-metrics"><Metric label="手元資金" value={compact(state.cash)}/><Metric label="今週の利益予測" value={compact(forecast.netProfit)} good={forecast.netProfit>0}/><Metric label="企業価値" value={compact(summary.valuation)}/></div>{designButton}<div className="week"><span>YEAR {Math.floor((state.week-1)/52)+1}</span><strong>第 {state.week} 週</strong><small><Pause size={10}/> 計画中</small></div></header><div className="body-layout"><section className={'main-area '+(page==='city'?'city-area':'')}>
  {page === 'city' ? <><CityView state={state} selectedLotId={selectedLotId} onSelectLot={selectLot} quality={state.settings.quality} viewMode={viewMode} focusLotId={selectedLotId} focusRailDistrict={focusRailDistrict} focusStoreLotId={focusStoreLotId}/><div className="city-heading"><span className="eyebrow">{focusStoreLotId && store ? "あなたのカフェ" : "街と事業を育てる"}</span><h2>{focusStoreLotId && store ? store.name : <>渋谷区 <span>SHIBUYA</span></>}</h2><p>{focusStoreLotId && store && lot ? `${districtNames[lot.district]} · ${styles[store.style]}` : "建物を選んで、次の一手を。"}</p></div><div className="map-controls">{(focusRailDistrict||focusStoreLotId)&&<button onClick={()=>{setFocusRailDistrict(null);setFocusStoreLotId(null);}}>街全体に戻る</button>}{(['normal','demand','ownership'] as const).map((v,i)=><button key={v} className={viewMode===v?'active':''} onClick={()=>setViewMode(v)}>{['街並み','需要分布','所有物件'][i]}</button>)}</div><div className="map-hint">ドラッグで回転 · ホイールで拡大 · 建物をクリックで選択</div><div className="map-coordinate">TOKYO / 35.6595° N, 139.7005° E</div></> : <div className="page-content"><div className="page-title"><span className="eyebrow">SHIBUYA CAPITAL / 経営</span><h2>{tabs.find(t=>t.id===page)?.label}</h2></div>
  {page==='development' && <><DevelopmentPanel state={state} onAction={act} busy={busy}/><RailProjectsPanel state={state} onAction={act} busy={busy} onPlanInvestment={planInvestment} investmentVisit={investmentVisit} onShowProject={districtId=>{setSelectedLotId(null);setFocusStoreLotId(null);setFocusRailDistrict(districtId);setPage('city');}}/></>}
  {page==='progression' && <ProgressionPanel state={state} onNavigate={tab=>setPage(tab as Page)}/>}
  {page==='stores' && <><div className="summary-strip"><Metric label="店舗数" value={`${state.stores.length} 店`}/><Metric label="累計来店者" value={`${state.totalCustomers.toLocaleString()} 人`}/><Metric label="ブランド評価" value={state.reputation.toFixed(0)}/></div>{!state.stores.length ? <div className="empty"><Coffee size={40}/><h3>最初の一杯から始めよう。</h3><p>渋谷の物件を選び、あなたの1号店を開業しましょう。</p><button className="primary" onClick={()=>setPage('city')}>街で物件を探す</button></div>:<div className="store-grid">{state.stores.map(s=><article className="card" key={s.id}><header><div><span className="eyebrow">{styles[s.style]} / LEVEL {s.level}</span><h3>{s.name}</h3></div><button className="icon-button" title="店の様子を見る" aria-label={`${s.name}の様子を見る`} onClick={()=>viewStore(s.lotId)}><MapPin size={18}/></button></header><div className="mini-metrics"><Metric label="前週利益" value={compact(s.profit)} good={s.profit>=0}/><Metric label="満足度" value={`${Math.round(s.satisfaction)}%`}/></div>{storeControls(s)}</article>)}</div>}</>}
  {page==='finance' && <><div className="summary-strip"><Metric label="手元資金" value={compact(state.cash)}/><Metric label="借入残高" value={compact(summary.debt)}/><Metric label="純資産" value={compact(summary.netWorth)}/></div><CapitalPlanningPanel state={state} onAction={act} disabled={busy||state.gameOver} planningContext={investmentPlan?.memo} onReturnToInvestment={returnToInvestment} initialDraft={financeDraft} onDraftChange={setFinanceDraft}/><div className="two-columns"><section className="card"><h3>借入契約</h3>{!state.loans.length && <p className="muted">借入はありません。</p>}{state.loans.map(l=><div className="list-row" key={l.id}><div><strong>{money(l.remaining)}</strong><small>年利 {(l.annualRate*100).toFixed(1)}% · 残り{l.weeksLeft}週</small></div>{actionButton('一括返済',{type:'repayLoan',loanId:l.id})}</div>)}</section></div><h3 className="section-title">保有不動産 <span>{state.properties.length} PROPERTIES</span></h3>{!state.properties.length?<div className="empty small"><Building2 size={28}/><p>地図上の物件から購入できます。賃貸収入を次の事業へ。</p><button className="secondary" onClick={()=>setPage('city')}>物件を探す</button></div>:<div className="store-grid">{state.properties.map(p=><article className="card" key={p.id}><span className="eyebrow">PROPERTY / LEVEL {p.level}</span><h3>{LOTS.find(l=>l.id===p.lotId)?.name}</h3><div className="mini-metrics"><Metric label={state.stores.some(s=>s.lotId===p.lotId)?"自社利用・家賃節約":"週間賃料の基準"} value={money(state.stores.some(s=>s.lotId===p.lotId)?(LOTS.find(l=>l.id===p.lotId)?.rent??0)*economy.rents:p.weeklyIncome*p.occupancy*economy.rents)}/><Metric label="稼働率" value={`${Math.round(p.occupancy*100)}%`}/></div><div className="button-row">{actionButton(`改修 ${compact(p.purchasePrice*.12)}`,{type:'upgradeProperty',propertyId:p.id})}<button className="danger-link" disabled={state.gameOver} onClick={()=>{if(window.confirm(`この不動産を ${money(p.purchasePrice*(1+(p.level-1)*.10)*.9)} で売却しますか？`)) act({type:'sellProperty',propertyId:p.id});}}>売却</button><button className="icon-button" onClick={()=>selectLot(p.lotId)} title="地図で見る"><MapPin size={17}/></button></div></article>)}</div>}</>}
  {page==='stocks' && <MarketPanel initialSection={marketEntry} state={state} onAction={act} busy={busy} onPlanInvestment={planInvestment} investmentVisit={investmentVisit}/>}
  {page==='deals' && <DealsPanel state={state} onAction={act} busy={busy}/>}
  {page==='group' && <><div className="summary-strip"><Metric label="企業価値" value={compact(summary.valuation)}/><Metric label="創業者持分" value={`${(summary.ownership*100).toFixed(1)}%`}/><Metric label="子会社" value={`${state.subsidiaries.length} 社`}/></div><section className="card ipo-card"><div><span className="eyebrow">資本政策</span><h3>{state.listed?'上場企業として、その先へ。':'東京から、株式市場へ。'}</h3>{!state.listed?<div className="requirements">{summary.ipoRequirements.map(r=><span key={r.label} className={r.met?'met':''}>{r.met?'✓':'○'} {r.label}</span>)}</div>:<p className="muted">発行済株式 {state.sharesOutstanding.toLocaleString()} 株 · 株価 {money(state.sharePrice)}</p>}</div>{!state.listed?<button className="primary" onClick={()=>setPage('finance')}>公開後の資金と持分を比較</button>:<div className="ipo-actions"><button className="secondary" onClick={()=>setPage('finance')}>増資と借入を比較</button><label>配当性向<select value={state.dividendPayout} onChange={e=>act({type:'setDividend',payout:Number(e.target.value)})}>{[0,0.1,0.25,0.5].map(v=><option key={v} value={v}>{v*100}%</option>)}</select></label></div>}</section><h3 className="section-title">事業を広げる <span>MERGERS & ACQUISITIONS</span></h3><div className="store-grid">{ACQUISITION_TARGETS.map(t=>{const owned=state.subsidiaries.some(s=>s.id===t.id);return <article className="card acquisition" key={t.id}><span className="eyebrow">{{food:'FOOD & BEVERAGE',property:'REAL ESTATE',rail:'RAILWAY'}[t.sector]}</span><h3>{t.name}</h3><p>{t.description}</p><div className="mini-metrics"><Metric label="買収価格" value={compact(t.price)}/><Metric label="週間利益の目安" value={compact(t.weeklyProfit)}/></div><small className="muted">必要ブランド評価 {t.minReputation} · 事業リスク {(t.risk*100).toFixed(0)}%</small>{owned?<span className="owned-label">グループ傘下</span>:actionButton('買収する',{type:'acquire',targetId:t.id},'primary')}</article>;})}</div></>}
  {page==='history' && <><div className="summary-strip"><Metric label="経営期間" value={`${state.week-1} 週`}/><Metric label="利益を出した週" value={`${state.profitableWeeks} 週`}/><Metric label="累計来店者" value={state.totalCustomers.toLocaleString()}/></div><OpeningResults state={state} onViewStore={viewStore} mode="history" onSelectStore={selectLot} onNavigate={tab=>{setSelectedLotId(null);setFocusRailDistrict(null);setFocusStoreLotId(null);setPage(tab);}}/><section className="card"><span className="eyebrow">企業価値の記録</span><h3>企業価値の軌跡</h3>{state.history.length<2?<p className="muted">週を進めると成長の記録が表示されます。</p>:<div className="chart"><svg viewBox="0 0 800 200" role="img" aria-label="企業価値の推移"><defs><linearGradient id="chartFill" x1="0" y1="0" x2="0" y2="1"><stop stopColor="var(--accent)" stopOpacity=".35"/><stop offset="1" stopColor="var(--accent)" stopOpacity="0"/></linearGradient></defs>{[40,90,140,190].map(y=><line key={y} x1="0" x2="800" y1={y} y2={y} stroke="var(--line)"/>)}{(()=>{const points=state.history;const max=Math.max(...points.map(p=>p.valuation),1);const min=Math.min(...points.map(p=>p.valuation),0);const coords=points.map((p,i)=>`${i/(points.length-1)*800},${190-(p.valuation-min)/(max-min||1)*170}`).join(' ');return <><polygon points={`0,200 ${coords} 800,200`} fill="url(#chartFill)"/><polyline points={coords} fill="none" stroke="var(--accent)" strokeWidth="3"/></>;})()}</svg><div className="chart-axis"><span>第{state.history[0].week}週</span><span>第{state.history[state.history.length-1].week}週</span></div></div>}</section><div className="table-wrap"><table><thead><tr><th>週</th><th>売上</th><th>純利益</th><th>手元資金</th><th>店舗数</th></tr></thead><tbody>{[...state.history].reverse().slice(0,100).map(h=><tr key={h.week}><td>第{h.week}週</td><td>{money(h.revenue)}</td><td className={h.profit>0?'positive':'negative'}>{money(h.profit)}</td><td>{money(h.cash)}</td><td>{h.stores}</td></tr>)}</tbody></table></div></>}
  </div>}</section>
  {page==='city' && <aside className="inspector">{lot?<><div className="inspector-title"><span className="eyebrow">{districtNames[lot.district]} / PROPERTY</span><button className="icon-button" aria-label="選択を解除" onClick={()=>setSelectedLotId(null)}><X size={18}/></button></div><h2>{lot.name}</h2><p className="muted">{lot.description}</p><div className="lot-visual"><Building2 size={60} strokeWidth={.8}/><span>{store?'YOUR COFFEE SHOP':property?'YOUR PROPERTY':'A NEW POSSIBILITY'}</span></div><div className="mini-metrics"><Metric label="通行量" value={lot.footfall.toLocaleString()}/><Metric label="客層の購買力" value={lot.affluence.toFixed(1)}/></div>{store?<><div className="section-rule"><h3>{store.name}</h3><span>営業中</span></div><div className="mini-metrics"><Metric label="前週売上" value={compact(store.revenue)}/><Metric label="前週利益" value={compact(store.profit)} good={store.profit>0}/></div><button className="secondary" onClick={()=>viewStore(store.lotId)}>店の様子を見る</button>{storeControls(store)}</>:lot.available?<StoreOpeningPanel state={state} lotId={lot.id} style={style} onStyleChange={setStyle} onOpen={chosen=>act({type:'openStore',lotId:lot.id,style:chosen})} onFinance={()=>planInvestment({kind:'store',lotId:lot.id,style})} disabled={busy||state.gameOver}/>:<p className="muted">この建物には出店できません。</p>}{property?<><div className="section-rule"><h3>所有不動産</h3><span>Lv.{property.level}</span></div><p>{store?`自社店舗の家賃 ${money(lot.rent*economy.rents)} / 週を節約`:`週間賃料の基準 ${money(property.weeklyIncome*property.occupancy*economy.rents)}`}</p>{actionButton(`物件を改修 ${compact(property.purchasePrice*.12)}`,{type:'upgradeProperty',propertyId:property.id})}</>:lot.available?<><div className="section-rule"><h3>不動産として保有</h3><Building2 size={17}/></div><p className="property-price">{money(lot.purchasePrice)}</p>{actionButton('物件を購入する',{type:'buyProperty',lotId:lot.id})}</>:null}</>:<><span className="eyebrow">渋谷エリアの出店候補</span><h2>次の挑戦は、<br/>この街にある。</h2><p className="muted">地図上の建物を選択して、出店条件や物件価格を比較しましょう。</p><div className="section-rule"><h3>出店候補</h3><MapPin size={17}/></div><div className="site-list">{LOTS.filter(l=>l.available&&!state.stores.some(s=>s.lotId===l.id)).slice(0,12).map(l=><button key={l.id} onClick={()=>selectLot(l.id)}><span><small>{districtNames[l.district]}</small><strong>{l.name}</strong><small>週家賃 {compact(l.rent)}</small></span><ChevronRight size={16}/></button>)}</div></>}{onboarding && <div className="onboarding"><button aria-label="ガイドを閉じる" onClick={()=>setOnboarding(false)}><X size={14}/></button><span className="eyebrow">経営のヒント</span><h3>{!state.stores.length?'まずは1号店を。':state.week===1?'最初の1週間を始めよう。':state.stores.length===1?'利益を、次の一歩へ。':'経営の舞台を広げよう。'}</h3><p>{!state.stores.length?'候補地の家賃と利益予測を比べ、初期資金でカフェを開業しましょう。':state.week===1?'価格とスタッフを整えたら「週を終了」。収支を確認して営業を始めます。':state.stores.length===1?'週次報告を確認して改善。資金が育ったら2号店を探しましょう。':'店長への委任、不動産、株式投資。会社に合う成長の道を選びましょう。'}</p></div>}</aside>}
  </div><footer className="bottom-bar"><div className="status-line"><i className={state.gameOver?'red':''}/><span>{state.gameOver?'経営終了':`${state.stores.length} 店舗 · ${state.properties.length} 物件 · ${state.subsidiaries.length} 子会社`}</span><small>{saved?.week===state.week?'週次保存あり':'週末に自動保存'}</small></div><button className="end-week" disabled={busy||state.gameOver} onClick={()=>setModal('week')}><span>週を終了する<small>収支を確認して、第{state.week+1}週へ</small></span><ArrowUpRight size={23}/></button></footer></div>{fileInput}
  {message && <div className="toast" role="alert">{message}<button aria-label="閉じる" onClick={()=>setMessage('')}><X size={16}/></button></div>}
  {state.gameOver && modal!=='settings' && <div className="game-over-banner"><strong>経営を終了しました</strong><span>{state.gameOverReason}</span><button onClick={()=>setModal('settings')}>記録の保存・新しい会社</button></div>}
  {modal==='week' && <Modal title={`第${state.week}週の営業計画`} close={()=>!busy&&setModal(null)}><p className="muted">現在の設定で営業し、結果と会社データを保存します。</p>{state.profitableWeeks>=12&&<><label>営業を進める期間<select disabled={busy} value={runWeeks} onChange={e=>setRunWeeks(Number(e.target.value) as 1|4|13)}><option value="1">1週間 · 決算を確認</option><option value="4">最大4週間 · 計画どおりに営業</option><option value="13">最大13週間 · 計画どおりに営業</option></select></label>{runWeeks>1&&<p className="muted">毎週保存し、新しい営業提案・上場機会・開発完了・資金不足の予測で止まります。途中で停止できます。下の収支は最初の1週間です。</p>}</>}{busy&&runWeeks>1&&<div className="batch-progress" role="status"><p>{batchDone} / {runWeeks} 週間の営業・保存が完了</p><button className="secondary" onClick={()=>{stopRun.current=true;}}>ここで停止</button></div>}<div className="summary-strip"><Metric label="売上予測" value={money(forecast.revenue)}/><Metric label="純利益予測" value={money(forecast.netProfit)} good={forecast.netProfit>0}/></div><dl className="cost-list"><div><dt>本部・グループ運営費（営業利益に算入済み）</dt><dd>{money(economy.overhead)}</dd></div><div><dt>営業利益</dt><dd>{money(forecast.operatingProfit)}</dd></div><div><dt>支払利息</dt><dd>{money(forecast.interest)}</dd></div><div><dt>元本返済</dt><dd>{money(forecast.loanRepayment)}</dd></div><div><dt>受取配当</dt><dd>{money(forecast.dividendsReceived)}</dd></div><div><dt>支払配当</dt><dd>{money(forecast.dividendsPaid)}</dd></div><div><dt>週末の資金予測</dt><dd>{money(state.cash+forecast.cashChange)}</dd></div></dl>{summary.debt>0&&forecast.netProfit<=0?<p className="warning danger">倒産の見込みがあります。借入残高があり、この週の純利益が0以下です。店舗設定の改善や借入の返済を検討してください。</p>:state.cash+forecast.cashChange<0?<p className="warning danger">週末に資金が不足する見込みです。営業を進める前に資金計画を見直してください。</p>:<p className="muted">現在の設定でこの週を決算します。設定や投資を変えると予測も更新されます。</p>}<div className="button-row"><button className="secondary" disabled={busy} onClick={()=>setModal(null)}>計画に戻る</button><button className="primary" disabled={busy} onClick={()=>void finishWeek()}>{busy?'営業・保存中…':runWeeks===1?'営業して週を進める':`最大${runWeeks}週間の営業を始める`}<ArrowUpRight size={18}/></button></div></Modal>}
  {modal==='batch'&&batchResult&&<Modal title="連続営業の報告" close={()=>setModal(null)}><p>第{batchResult.reports[0]?.week}週から {batchResult.reports.length} 週間の営業を完了しました。各週の会社データを保存しています。</p><div className="summary-strip"><Metric label="期間の純利益" value={money(batchResult.reports.reduce((n,r)=>n+r.netProfit,0))} good={batchResult.reports.reduce((n,r)=>n+r.netProfit,0)>0}/><Metric label="期間の現金増減" value={money(batchResult.reports.reduce((n,r)=>n+r.cashChange,0))}/></div>{batchResult.stopReason&&<p className="warning">{batchResult.stopReason}</p>}<OpeningResults state={state} onViewStore={viewStore} reportWeeks={batchResult.reports.map(r=>r.week)} onSelectStore={id=>{setModal(null);selectLot(id);}} onNavigate={tab=>{setModal(null);setSelectedLotId(null);setFocusRailDistrict(null);setFocusStoreLotId(null);setPage(tab);}} onContinue={()=>setModal(null)}/><div className="table-wrap"><table><thead><tr><th>営業週</th><th>純利益</th><th>現金増減</th></tr></thead><tbody>{batchResult.reports.map(r=><tr key={r.week}><td>第{r.week}週</td><td className={r.netProfit>0?'positive':'negative'}>{money(r.netProfit)}</td><td>{money(r.cashChange)}</td></tr>)}</tbody></table></div><div className="button-row"><button className="secondary" onClick={()=>setModal('report')}>最後の週の詳細</button><button className="primary" onClick={()=>setModal(null)}>経営に戻る<ChevronRight size={18}/></button></div></Modal>}
  {modal==='report' && state.lastReport && <Modal title={`第${state.lastReport.week}週の経営レポート`} close={()=>setModal(null)}><div className="report-intro"><span className="report-symbol">{state.lastReport.netProfit>0?<ArrowUpRight size={36}/>:<ArrowDownLeft size={36}/>}</span><div><span className="eyebrow">今週の純利益</span><h3 className={state.lastReport.netProfit>0?'positive':'negative'}>{money(state.lastReport.netProfit)}</h3></div></div><div className="mini-metrics"><Metric label="週間売上" value={money(state.lastReport.revenue)}/><Metric label="来店者数" value={`${state.lastReport.customers.toLocaleString()} 人`}/></div><OpeningResults state={state} onViewStore={viewStore} onSelectStore={id=>{setModal(null);selectLot(id);}} onNavigate={tab=>{setModal(null);setSelectedLotId(null);setFocusRailDistrict(null);setFocusStoreLotId(null);setPage(tab);}} onContinue={()=>setModal(null)}/><div className="report-news">{state.lastReport.headlines.map((h,i)=><p key={i}><span>0{i+1}</span>{h}</p>)}</div>{state.gameOver&&<p className="warning danger">{state.gameOverReason}</p>}<p className="save-confirm">✓ 第{state.week}週の会社データを保存しました</p><button className="primary" onClick={()=>setModal(null)}>街に戻る<ChevronRight size={18}/></button></Modal>}
  {modal==='settings' && <Modal title="設定と会社データ" close={()=>!busy&&setModal(null)} wide><div className="two-columns"><section><h3>表示品質</h3><label>3D描画<select value={state.settings.quality} onChange={e=>act({type:'settings',changes:{quality:e.target.value as GameState['settings']['quality']}})}><option value="low">軽量 · ノートPC向け</option><option value="medium">標準</option><option value="high">高品質</option></select></label><p className="muted">経営は「週を終了」したときだけ進みます。</p><button className="secondary" disabled={busy} onClick={()=>void openRealCity()}>保存して実際の渋谷を3Dで見る</button><h3>保存と持ち出し</h3><p className="muted">週終了時に自動保存します。長く遊ぶ会社は、定期的にファイルへ書き出してください。</p><div className="stack-buttons"><button className="primary" disabled={busy} onClick={()=>void save()}>今すぐ保存する</button><button className="secondary" disabled={busy} onClick={()=>{void Promise.resolve(exportGame(state)).catch(fail);}}>保存ファイルを書き出す</button><button className="secondary" disabled={busy} onClick={()=>{if(window.confirm('現在の会社を読み込むファイルの内容で置き換えます。続けますか？'))fileRef.current?.click();}}>ファイルから読み込む</button></div></section><section><h3>週次バックアップ</h3><p className="muted">過去の時点に戻せます。現在の進行は置き換わります。</p><div className="backup-list">{!backups.length?<p>バックアップはまだありません。</p>:backups.map(b=><div className="list-row" key={b.key}><div><strong>{b.companyName}</strong><small>第{b.week}週 · {new Date(b.savedAt).toLocaleString('ja-JP')}</small></div><button className="secondary" disabled={busy} onClick={()=>{if(window.confirm(`第${b.week}週のバックアップを復元しますか？`))void restore(b.key);}}>復元</button></div>)}</div><div className="section-rule"><h3>新しい物語</h3></div><button className="danger-link" disabled={busy} onClick={()=>setModal('new')}>新しい会社を設立する</button></section></div></Modal>}
  {modal==='new' && <Modal title="新しい会社を設立" close={()=>setModal('settings')}><p>現在の会社を新しい会社に置き換えます。続ける前に保存ファイルを書き出すことをおすすめします。</p><button className="secondary" onClick={()=>{void Promise.resolve(exportGame(state)).catch(fail);}}>現在の会社を書き出す</button><label>会社名<input value={companyName} maxLength={40} onChange={e=>setCompanyName(e.target.value)}/></label><button className="primary" disabled={busy} onClick={()=>void start()}>新しい会社を設立する</button></Modal>}
  </main>;
}
